#!/bin/bash
echo "This issue is being generated by script to prompt maintainers to add
links to support channels (such as slack channels, discord channels, or other chats).

It is accompanied by a draft PR appending a placeholder section to the repository's
README.

In the event that a repository has a private or invite-only support channel
(such as a private slack or discord), we ask that you at least indicate the
existence of such a channel so that non-members can be aware of teammates who
may have access to these channels."
